project:
  type: book
  output-dir: docs

book:
  title: "Identifying Levers: An Introduction to Causal Inference in Business"
  author: "Brandon Scott"
  date: "5/12/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cyborg
  pdf:
    documentclass: scrreprt



